### ISSUE TITLE
ArgumentNullException when ToContainer is not called during entity configuration

### ISSUE THREAD

**Issue by steve-warren** [steve-warren/cosmo-dust#42]
```
System.ArgumentNullException: Value cannot be null. (Parameter 'id')
   at Microsoft.Azure.Cosmos.DatabaseCore.GetContainer(String id)
   at Microsoft.Azure.Cosmos.DatabaseInlineCore.GetContainer(String id)
   at Cosmodust.Cosmos.CosmosDatabase.GetContainerFor(String containerName) in CosmosDatabase.cs:line 116
   at Cosmodust.Cosmos.CosmosDatabase.CreateOperation(EntityEntry entry) in CosmosDatabase.cs:line 100
   at Cosmodust.Cosmos.CosmosDatabase.CommitAsync(IEnumerable`1 entries, CancellationToken cancellationToken) in CosmosDatabase.cs:line 65
   at Cosmodust.DocumentSession.CommitAsync(CancellationToken cancellationToken) in DocumentSession.cs:line 78
```

**Comment by steve-warren** [comment]
Unable to reproduce.
